import { config, fields, singleton } from '@keystatic/core';

const hasGithubEnv = !!(
  process.env.KEYSTATIC_GITHUB_CLIENT_ID &&
  process.env.KEYSTATIC_GITHUB_CLIENT_SECRET &&
  process.env.KEYSTATIC_SECRET
);

export default config({
  storage:
    process.env.NODE_ENV === 'production'
      ? {
          kind: 'github',
          repo: 'smc1992/oaza-mira-website',
        }
      : {
          kind: 'local',
        },
  singletons: {
    deTranslations: singleton({
      label: 'Deutsche Übersetzungen (de.json)',
      path: 'src/dictionaries/de',
      format: { data: 'json' },
      schema: {
      'nav.home': fields.text({ label: 'nav ➔ home' }),
      'nav.services': fields.text({ label: 'nav ➔ services' }),
      'nav.families': fields.text({ label: 'nav ➔ families' }),
      'nav.companies': fields.text({ label: 'nav ➔ companies' }),
      'nav.caretakers': fields.text({ label: 'nav ➔ caretakers' }),
      'nav.institutions': fields.text({ label: 'nav ➔ institutions' }),
      'nav.howItWorks': fields.text({ label: 'nav ➔ how It Works' }),
      'nav.about': fields.text({ label: 'nav ➔ about' }),
      'nav.targetGroups': fields.text({ label: 'nav ➔ target Groups' }),
      'nav.contact': fields.text({ label: 'nav ➔ contact' }),
      'btn.login': fields.text({ label: 'btn ➔ login' }),
      'btn.signup': fields.text({ label: 'btn ➔ signup' }),
      'hero.title': fields.text({ label: 'hero ➔ title' }),
      'hero.subtitle': fields.text({ label: 'hero ➔ subtitle' }),
      'hero.cta.primary': fields.text({ label: 'hero ➔ cta ➔ primary' }),
      'hero.cta.secondary': fields.text({ label: 'hero ➔ cta ➔ secondary' }),
      'howitworks.eyebrow': fields.text({ label: 'howitworks ➔ eyebrow' }),
      'howitworks.title': fields.text({ label: 'howitworks ➔ title' }),
      'howitworks.subtitle': fields.text({ label: 'howitworks ➔ subtitle' }),
      'howitworks.steps.title': fields.text({ label: 'howitworks ➔ steps ➔ title' }),
      'howitworks.steps.subtitle': fields.text({ label: 'howitworks ➔ steps ➔ subtitle' }),
      'howitworks.step1.title': fields.text({ label: 'howitworks ➔ step1 ➔ title' }),
      'howitworks.step1.desc': fields.text({ label: 'howitworks ➔ step1 ➔ desc' }),
      'howitworks.step2.title': fields.text({ label: 'howitworks ➔ step2 ➔ title' }),
      'howitworks.step2.desc': fields.text({ label: 'howitworks ➔ step2 ➔ desc' }),
      'howitworks.step3.title': fields.text({ label: 'howitworks ➔ step3 ➔ title' }),
      'howitworks.step3.desc': fields.text({ label: 'howitworks ➔ step3 ➔ desc' }),
      'howitworks.step4.title': fields.text({ label: 'howitworks ➔ step4 ➔ title' }),
      'howitworks.step4.desc': fields.text({ label: 'howitworks ➔ step4 ➔ desc' }),
      'howitworks.features.title': fields.text({ label: 'howitworks ➔ features ➔ title' }),
      'howitworks.features.subtitle': fields.text({ label: 'howitworks ➔ features ➔ subtitle' }),
      'howitworks.feature1.title': fields.text({ label: 'howitworks ➔ feature1 ➔ title' }),
      'howitworks.feature1.desc': fields.text({ label: 'howitworks ➔ feature1 ➔ desc' }),
      'howitworks.feature2.title': fields.text({ label: 'howitworks ➔ feature2 ➔ title' }),
      'howitworks.feature2.desc': fields.text({ label: 'howitworks ➔ feature2 ➔ desc' }),
      'howitworks.feature3.title': fields.text({ label: 'howitworks ➔ feature3 ➔ title' }),
      'howitworks.feature3.desc': fields.text({ label: 'howitworks ➔ feature3 ➔ desc' }),
      'howitworks.feature4.title': fields.text({ label: 'howitworks ➔ feature4 ➔ title' }),
      'howitworks.feature4.desc': fields.text({ label: 'howitworks ➔ feature4 ➔ desc' }),
      'howitworks.feature5.title': fields.text({ label: 'howitworks ➔ feature5 ➔ title' }),
      'howitworks.feature5.desc': fields.text({ label: 'howitworks ➔ feature5 ➔ desc' }),
      'howitworks.feature6.title': fields.text({ label: 'howitworks ➔ feature6 ➔ title' }),
      'howitworks.feature6.desc': fields.text({ label: 'howitworks ➔ feature6 ➔ desc' }),
      'howitworks.testimonials.title': fields.text({ label: 'howitworks ➔ testimonials ➔ title' }),
      'howitworks.testimonials.subtitle': fields.text({ label: 'howitworks ➔ testimonials ➔ subtitle' }),
      'howitworks.testimonial1': fields.text({ label: 'howitworks ➔ testimonial1' }),
      'howitworks.testimonial2': fields.text({ label: 'howitworks ➔ testimonial2' }),
      'howitworks.testimonial3': fields.text({ label: 'howitworks ➔ testimonial3' }),
      'howitworks.cta.title': fields.text({ label: 'howitworks ➔ cta ➔ title' }),
      'howitworks.cta.subtitle': fields.text({ label: 'howitworks ➔ cta ➔ subtitle' }),
      'howitworks.cta.primary': fields.text({ label: 'howitworks ➔ cta ➔ primary' }),
      'howitworks.cta.secondary': fields.text({ label: 'howitworks ➔ cta ➔ secondary' }),
      'plans.eyebrow': fields.text({ label: 'plans ➔ eyebrow' }),
      'plans.title': fields.text({ label: 'plans ➔ title' }),
      'plans.subtitle': fields.text({ label: 'plans ➔ subtitle' }),
      'plans.basic.title': fields.text({ label: 'plans ➔ basic ➔ title' }),
      'plans.basic.desc': fields.text({ label: 'plans ➔ basic ➔ desc' }),
      'plans.premium.title': fields.text({ label: 'plans ➔ premium ➔ title' }),
      'plans.premium.desc': fields.text({ label: 'plans ➔ premium ➔ desc' }),
      'btn.register': fields.text({ label: 'btn ➔ register' }),
      'app.eyebrow': fields.text({ label: 'app ➔ eyebrow' }),
      'app.title': fields.text({ label: 'app ➔ title' }),
      'app.subtitle': fields.text({ label: 'app ➔ subtitle' }),
      'app.apple': fields.text({ label: 'app ➔ apple' }),
      'app.google': fields.text({ label: 'app ➔ google' }),
      'cta.final': fields.text({ label: 'cta ➔ final' }),
      'btn.contact': fields.text({ label: 'btn ➔ contact' }),
      'families.8obkup': fields.text({ label: 'families ➔ 8obkup' }),
      'families.g98to4': fields.text({ label: 'families ➔ g98to4' }),
      'families.qec43n': fields.text({ label: 'families ➔ qec43n' }),
      'families.hxhsi0': fields.text({ label: 'families ➔ hxhsi0' }),
      'families.4rf7pp': fields.text({ label: 'families ➔ 4rf7pp' }),
      'families.hj40w3': fields.text({ label: 'families ➔ hj40w3' }),
      'families.ffxrqu': fields.text({ label: 'families ➔ ffxrqu' }),
      'families.rnq6i6': fields.text({ label: 'families ➔ rnq6i6' }),
      'families.1vttbc': fields.text({ label: 'families ➔ 1vttbc' }),
      'btn.baz63n': fields.text({ label: 'btn ➔ baz63n' }),
      'btn.tajlr7': fields.text({ label: 'btn ➔ tajlr7' }),
      'btn.kbxonb': fields.text({ label: 'btn ➔ kbxonb' }),
      'btn.ss7pm7': fields.text({ label: 'btn ➔ ss7pm7' }),
      'business.yucpi8': fields.text({ label: 'business ➔ yucpi8' }),
      'business.jfxwf7': fields.text({ label: 'business ➔ jfxwf7' }),
      'business.2cyre1': fields.text({ label: 'business ➔ 2cyre1' }),
      'business.ylyczm': fields.text({ label: 'business ➔ ylyczm' }),
      'business.ffxrqu': fields.text({ label: 'business ➔ ffxrqu' }),
      'business.rnq6i6': fields.text({ label: 'business ➔ rnq6i6' }),
      'business.1vttbc': fields.text({ label: 'business ➔ 1vttbc' }),
      'institutions.db2gj4': fields.text({ label: 'institutions ➔ db2gj4' }),
      'institutions.qapkqs': fields.text({ label: 'institutions ➔ qapkqs' }),
      'institutions.r1j4o5': fields.text({ label: 'institutions ➔ r1j4o5' }),
      'institutions.3dylv3': fields.text({ label: 'institutions ➔ 3dylv3' }),
      'institutions.rnq6i6': fields.text({ label: 'institutions ➔ rnq6i6' }),
      'institutions.1vttbc': fields.text({ label: 'institutions ➔ 1vttbc' }),
      'btn.za3mim': fields.text({ label: 'btn ➔ za3mim' }),
      'btn.wxrlhb': fields.text({ label: 'btn ➔ wxrlhb' }),
      'providers.tgm1nq': fields.text({ label: 'providers ➔ tgm1nq' }),
      'providers.1ep91': fields.text({ label: 'providers ➔ 1ep91' }),
      'providers.9qrh41': fields.text({ label: 'providers ➔ 9qrh41' }),
      'providers.rnq6i6': fields.text({ label: 'providers ➔ rnq6i6' }),
      'providers.1vttbc': fields.text({ label: 'providers ➔ 1vttbc' }),
      'btn.pjun8n': fields.text({ label: 'btn ➔ pjun8n' }),
      'btn.pjtzif': fields.text({ label: 'btn ➔ pjtzif' }),
      'about.lltg2z': fields.text({ label: 'about ➔ lltg2z' }),
      'about.5i94sz': fields.text({ label: 'about ➔ 5i94sz' }),
      'about.qje0vl': fields.text({ label: 'about ➔ qje0vl' }),
      'about.bmciuz': fields.text({ label: 'about ➔ bmciuz' }),
      'about.fyalyk': fields.text({ label: 'about ➔ fyalyk' }),
      'about.c8lysq': fields.text({ label: 'about ➔ c8lysq' }),
      'about.19u3im': fields.text({ label: 'about ➔ 19u3im' }),
      'about.ffnspn': fields.text({ label: 'about ➔ ffnspn' }),
      'about.g1bwny': fields.text({ label: 'about ➔ g1bwny' }),
      'about.xjr5ai': fields.text({ label: 'about ➔ xjr5ai' }),
      'about.k51ypq': fields.text({ label: 'about ➔ k51ypq' }),
      'about.mk7xo6': fields.text({ label: 'about ➔ mk7xo6' }),
      'about.twhsw8': fields.text({ label: 'about ➔ twhsw8' }),
      'about.7mf0mf': fields.text({ label: 'about ➔ 7mf0mf' }),
      'about.w395tm': fields.text({ label: 'about ➔ w395tm' }),
      'about.neplkz': fields.text({ label: 'about ➔ neplkz' }),
      'about.uqz92y': fields.text({ label: 'about ➔ uqz92y' }),
      'about.re1vey': fields.text({ label: 'about ➔ re1vey' }),
      'about.rnq6i6': fields.text({ label: 'about ➔ rnq6i6' }),
      'btn.9urml2': fields.text({ label: 'btn ➔ 9urml2' }),
      'contact.1tr8yh': fields.text({ label: 'contact ➔ 1tr8yh' }),
      'contact.frg0dp': fields.text({ label: 'contact ➔ frg0dp' }),
      'contact.rnq6i6': fields.text({ label: 'contact ➔ rnq6i6' }),
      'contact.1vttbc': fields.text({ label: 'contact ➔ 1vttbc' }),
      'imprint.bn9ct3': fields.text({ label: 'imprint ➔ bn9ct3' }),
      'imprint.5vhr4f': fields.text({ label: 'imprint ➔ 5vhr4f' }),
      'imprint.cnghov': fields.text({ label: 'imprint ➔ cnghov' }),
      'imprint.jjo9k2': fields.text({ label: 'imprint ➔ jjo9k2' }),
      'imprint.1vttbc': fields.text({ label: 'imprint ➔ 1vttbc' }),
      'privacy-policy.hop62e': fields.text({ label: 'privacy-policy ➔ hop62e' }),
      'privacy-policy.if995r': fields.text({ label: 'privacy-policy ➔ if995r' }),
      'privacy-policy.ry02dm': fields.text({ label: 'privacy-policy ➔ ry02dm' }),
      'privacy-policy.eniysn': fields.text({ label: 'privacy-policy ➔ eniysn' }),
      'privacy-policy.jh3mop': fields.text({ label: 'privacy-policy ➔ jh3mop' }),
      'privacy-policy.1tw77k': fields.text({ label: 'privacy-policy ➔ 1tw77k' }),
      'privacy-policy.spkljn': fields.text({ label: 'privacy-policy ➔ spkljn' }),
      'privacy-policy.7rv48p': fields.text({ label: 'privacy-policy ➔ 7rv48p' }),
      'privacy-policy.ecgqqb': fields.text({ label: 'privacy-policy ➔ ecgqqb' }),
      'privacy-policy.2h4v5g': fields.text({ label: 'privacy-policy ➔ 2h4v5g' }),
      'privacy-policy.mbws6u': fields.text({ label: 'privacy-policy ➔ mbws6u' }),
      'privacy-policy.n7kh4j': fields.text({ label: 'privacy-policy ➔ n7kh4j' }),
      'privacy-policy.qvfur5': fields.text({ label: 'privacy-policy ➔ qvfur5' }),
      'privacy-policy.ls2tnc': fields.text({ label: 'privacy-policy ➔ ls2tnc' }),
      'privacy-policy.nfj3mi': fields.text({ label: 'privacy-policy ➔ nfj3mi' }),
      'privacy-policy.ow8rze': fields.text({ label: 'privacy-policy ➔ ow8rze' }),
      'privacy-policy.n99qdx': fields.text({ label: 'privacy-policy ➔ n99qdx' }),
      'privacy-policy.ytl33c': fields.text({ label: 'privacy-policy ➔ ytl33c' }),
      'privacy-policy.51069v': fields.text({ label: 'privacy-policy ➔ 51069v' }),
      'privacy-policy.txt85s': fields.text({ label: 'privacy-policy ➔ txt85s' }),
      'privacy-policy.1vttbc': fields.text({ label: 'privacy-policy ➔ 1vttbc' }),
      'disclaimer-page.uwtyyt': fields.text({ label: 'disclaimer-page ➔ uwtyyt' }),
      'disclaimer-page.op3kb1': fields.text({ label: 'disclaimer-page ➔ op3kb1' }),
      'disclaimer-page.ahbulr': fields.text({ label: 'disclaimer-page ➔ ahbulr' }),
      'disclaimer-page.24ddz8': fields.text({ label: 'disclaimer-page ➔ 24ddz8' }),
      'disclaimer-page.6b333p': fields.text({ label: 'disclaimer-page ➔ 6b333p' }),
      'disclaimer-page.hhl8tl': fields.text({ label: 'disclaimer-page ➔ hhl8tl' }),
      'disclaimer-page.s9aat9': fields.text({ label: 'disclaimer-page ➔ s9aat9' }),
      'disclaimer-page.350ksq': fields.text({ label: 'disclaimer-page ➔ 350ksq' }),
      'disclaimer-page.numnp6': fields.text({ label: 'disclaimer-page ➔ numnp6' }),
      'disclaimer-page.aa0fux': fields.text({ label: 'disclaimer-page ➔ aa0fux' }),
      'disclaimer-page.l0g468': fields.text({ label: 'disclaimer-page ➔ l0g468' }),
      'disclaimer-page.8kpta6': fields.text({ label: 'disclaimer-page ➔ 8kpta6' }),
      'disclaimer-page.ajhmhl': fields.text({ label: 'disclaimer-page ➔ ajhmhl' }),
      'disclaimer-page.k5328e': fields.text({ label: 'disclaimer-page ➔ k5328e' }),
      'disclaimer-page.ef13ox': fields.text({ label: 'disclaimer-page ➔ ef13ox' }),
      'disclaimer-page.4vq4j4': fields.text({ label: 'disclaimer-page ➔ 4vq4j4' }),
      'disclaimer-page.rnq6i6': fields.text({ label: 'disclaimer-page ➔ rnq6i6' }),
      'disclaimer-page.1vttbc': fields.text({ label: 'disclaimer-page ➔ 1vttbc' }),
      'families.hero.badge': fields.text({ label: 'families ➔ hero ➔ badge' }),
      'families.hero.title1': fields.text({ label: 'families ➔ hero ➔ title1' }),
      'families.hero.title2': fields.text({ label: 'families ➔ hero ➔ title2' }),
      'families.hero.desc': fields.text({ label: 'families ➔ hero ➔ desc' }),
      'families.hero.cta': fields.text({ label: 'families ➔ hero ➔ cta' }),
      'families.how.title': fields.text({ label: 'families ➔ how ➔ title' }),
      'families.how.1.title': fields.text({ label: 'families ➔ how ➔ 1 ➔ title' }),
      'families.how.1.desc': fields.text({ label: 'families ➔ how ➔ 1 ➔ desc' }),
      'families.how.2.title': fields.text({ label: 'families ➔ how ➔ 2 ➔ title' }),
      'families.how.2.desc': fields.text({ label: 'families ➔ how ➔ 2 ➔ desc' }),
      'families.how.3.title': fields.text({ label: 'families ➔ how ➔ 3 ➔ title' }),
      'families.how.3.desc': fields.text({ label: 'families ➔ how ➔ 3 ➔ desc' }),
      'families.how.4.title': fields.text({ label: 'families ➔ how ➔ 4 ➔ title' }),
      'families.how.4.desc': fields.text({ label: 'families ➔ how ➔ 4 ➔ desc' }),
      'families.invite.title': fields.text({ label: 'families ➔ invite ➔ title' }),
      'families.invite.desc': fields.text({ label: 'families ➔ invite ➔ desc' }),
      'families.invite.cta': fields.text({ label: 'families ➔ invite ➔ cta' }),
      'families.know.title': fields.text({ label: 'families ➔ know ➔ title' }),
      'families.know.desc': fields.text({ label: 'families ➔ know ➔ desc' }),
      'families.know.cta': fields.text({ label: 'families ➔ know ➔ cta' }),
      'families.app.title': fields.text({ label: 'families ➔ app ➔ title' }),
      'families.app.desc': fields.text({ label: 'families ➔ app ➔ desc' }),
      'families.app.cta': fields.text({ label: 'families ➔ app ➔ cta' }),
      'business.hero.badge': fields.text({ label: 'business ➔ hero ➔ badge' }),
      'business.hero.title1': fields.text({ label: 'business ➔ hero ➔ title1' }),
      'business.hero.title2': fields.text({ label: 'business ➔ hero ➔ title2' }),
      'business.hero.desc': fields.text({ label: 'business ➔ hero ➔ desc' }),
      'business.hero.cta': fields.text({ label: 'business ➔ hero ➔ cta' }),
      'business.pillar1.title': fields.text({ label: 'business ➔ pillar1 ➔ title' }),
      'business.pillar1.desc': fields.text({ label: 'business ➔ pillar1 ➔ desc' }),
      'business.pillar2.title': fields.text({ label: 'business ➔ pillar2 ➔ title' }),
      'business.pillar2.desc': fields.text({ label: 'business ➔ pillar2 ➔ desc' }),
      'business.cta.title': fields.text({ label: 'business ➔ cta ➔ title' }),
      'business.cta.desc': fields.text({ label: 'business ➔ cta ➔ desc' }),
      'business.cta.btn': fields.text({ label: 'business ➔ cta ➔ btn' }),
      'institutions.hero.badge': fields.text({ label: 'institutions ➔ hero ➔ badge' }),
      'institutions.hero.title1': fields.text({ label: 'institutions ➔ hero ➔ title1' }),
      'institutions.hero.title2': fields.text({ label: 'institutions ➔ hero ➔ title2' }),
      'institutions.hero.desc': fields.text({ label: 'institutions ➔ hero ➔ desc' }),
      'institutions.hero.cta': fields.text({ label: 'institutions ➔ hero ➔ cta' }),
      'institutions.pillar1.title': fields.text({ label: 'institutions ➔ pillar1 ➔ title' }),
      'institutions.pillar1.desc': fields.text({ label: 'institutions ➔ pillar1 ➔ desc' }),
      'institutions.pillar2.title': fields.text({ label: 'institutions ➔ pillar2 ➔ title' }),
      'institutions.pillar2.desc': fields.text({ label: 'institutions ➔ pillar2 ➔ desc' }),
      'institutions.cta.title': fields.text({ label: 'institutions ➔ cta ➔ title' }),
      'institutions.cta.desc': fields.text({ label: 'institutions ➔ cta ➔ desc' }),
      'institutions.cta.btn': fields.text({ label: 'institutions ➔ cta ➔ btn' }),
      'institutions.steps.title': fields.text({ label: 'institutions ➔ steps ➔ title' }),
      'institutions.step1.title': fields.text({ label: 'institutions ➔ step1 ➔ title' }),
      'institutions.step1.desc': fields.text({ label: 'institutions ➔ step1 ➔ desc' }),
      'institutions.step2.title': fields.text({ label: 'institutions ➔ step2 ➔ title' }),
      'institutions.step2.desc': fields.text({ label: 'institutions ➔ step2 ➔ desc' }),
      'institutions.step3.title': fields.text({ label: 'institutions ➔ step3 ➔ title' }),
      'institutions.step3.desc': fields.text({ label: 'institutions ➔ step3 ➔ desc' }),
      'institutions.register.cta': fields.text({ label: 'institutions ➔ register ➔ cta' }),
      'providers.hero.badge': fields.text({ label: 'providers ➔ hero ➔ badge' }),
      'providers.hero.title1': fields.text({ label: 'providers ➔ hero ➔ title1' }),
      'providers.hero.title2': fields.text({ label: 'providers ➔ hero ➔ title2' }),
      'providers.hero.desc': fields.text({ label: 'providers ➔ hero ➔ desc' }),
      'providers.hero.cta': fields.text({ label: 'providers ➔ hero ➔ cta' }),
      'providers.steps.title': fields.text({ label: 'providers ➔ steps ➔ title' }),
      'providers.step1.title': fields.text({ label: 'providers ➔ step1 ➔ title' }),
      'providers.step1.desc': fields.text({ label: 'providers ➔ step1 ➔ desc' }),
      'providers.step2.title': fields.text({ label: 'providers ➔ step2 ➔ title' }),
      'providers.step2.desc': fields.text({ label: 'providers ➔ step2 ➔ desc' }),
      'providers.step3.title': fields.text({ label: 'providers ➔ step3 ➔ title' }),
      'providers.step3.desc': fields.text({ label: 'providers ➔ step3 ➔ desc' }),
      'providers.cta.title': fields.text({ label: 'providers ➔ cta ➔ title' }),
      'providers.cta.desc': fields.text({ label: 'providers ➔ cta ➔ desc' }),
      'providers.cta.btn': fields.text({ label: 'providers ➔ cta ➔ btn' }),
      'contact.badge': fields.text({ label: 'contact ➔ badge' }),
      'contact.title1': fields.text({ label: 'contact ➔ title1' }),
      'contact.title2': fields.text({ label: 'contact ➔ title2' }),
      'contact.desc': fields.text({ label: 'contact ➔ desc' }),
      'contact.email.title': fields.text({ label: 'contact ➔ email ➔ title' }),
      'contact.email.desc': fields.text({ label: 'contact ➔ email ➔ desc' }),
      'contact.phone.title': fields.text({ label: 'contact ➔ phone ➔ title' }),
      'contact.phone.desc': fields.text({ label: 'contact ➔ phone ➔ desc' }),
      'contact.office.title': fields.text({ label: 'contact ➔ office ➔ title' }),
      'contact.office.desc': fields.text({ label: 'contact ➔ office ➔ desc' }),
      'contact.newsletter.title': fields.text({ label: 'contact ➔ newsletter ➔ title' }),
      'contact.newsletter.desc': fields.text({ label: 'contact ➔ newsletter ➔ desc' }),
      'contact.newsletter.btn': fields.text({ label: 'contact ➔ newsletter ➔ btn' }),
      'providers.adv.title': fields.text({ label: 'providers ➔ adv ➔ title' }),
      'providers.adv.1.title': fields.text({ label: 'providers ➔ adv ➔ 1 ➔ title' }),
      'providers.adv.1.desc': fields.text({ label: 'providers ➔ adv ➔ 1 ➔ desc' }),
      'providers.adv.2.title': fields.text({ label: 'providers ➔ adv ➔ 2 ➔ title' }),
      'providers.adv.2.desc': fields.text({ label: 'providers ➔ adv ➔ 2 ➔ desc' }),
      'providers.adv.3.title': fields.text({ label: 'providers ➔ adv ➔ 3 ➔ title' }),
      'providers.adv.3.desc': fields.text({ label: 'providers ➔ adv ➔ 3 ➔ desc' }),
      'providers.adv.4.title': fields.text({ label: 'providers ➔ adv ➔ 4 ➔ title' }),
      'providers.adv.4.desc': fields.text({ label: 'providers ➔ adv ➔ 4 ➔ desc' }),
      'providers.app.title': fields.text({ label: 'providers ➔ app ➔ title' }),
      'providers.app.desc': fields.text({ label: 'providers ➔ app ➔ desc' }),
      'providers.app.cta': fields.text({ label: 'providers ➔ app ➔ cta' }),
      'about.label': fields.text({ label: 'about ➔ label' }),
      'about.impact': fields.text({ label: 'about ➔ impact' }),
      'contact.form.title': fields.text({ label: 'contact ➔ form ➔ title' }),
      'contact.form.desc': fields.text({ label: 'contact ➔ form ➔ desc' }),
      'contact.form.name.label': fields.text({ label: 'contact ➔ form ➔ name ➔ label' }),
      'contact.form.name.placeholder': fields.text({ label: 'contact ➔ form ➔ name ➔ placeholder' }),
      'contact.form.email.label': fields.text({ label: 'contact ➔ form ➔ email ➔ label' }),
      'contact.form.email.placeholder': fields.text({ label: 'contact ➔ form ➔ email ➔ placeholder' }),
      'contact.form.phone.label': fields.text({ label: 'contact ➔ form ➔ phone ➔ label' }),
      'contact.form.phone.placeholder': fields.text({ label: 'contact ➔ form ➔ phone ➔ placeholder' }),
      'contact.form.subject.label': fields.text({ label: 'contact ➔ form ➔ subject ➔ label' }),
      'contact.form.subject.placeholder': fields.text({ label: 'contact ➔ form ➔ subject ➔ placeholder' }),
      'contact.form.message.label': fields.text({ label: 'contact ➔ form ➔ message ➔ label' }),
      'contact.form.message.placeholder': fields.text({ label: 'contact ➔ form ➔ message ➔ placeholder' }),
      'contact.form.submit': fields.text({ label: 'contact ➔ form ➔ submit' }),
      'contact.newsletter.disclaimer': fields.text({ label: 'contact ➔ newsletter ➔ disclaimer' }),
      'teaser.badge': fields.text({ label: 'teaser ➔ badge' }),
      'teaser.title': fields.text({ label: 'teaser ➔ title' }),
      'teaser.desc': fields.text({ label: 'teaser ➔ desc' }),
      'teaser.feature1.title': fields.text({ label: 'teaser ➔ feature1 ➔ title' }),
      'teaser.feature1.desc': fields.text({ label: 'teaser ➔ feature1 ➔ desc' }),
      'teaser.feature2.title': fields.text({ label: 'teaser ➔ feature2 ➔ title' }),
      'teaser.feature2.desc': fields.text({ label: 'teaser ➔ feature2 ➔ desc' }),
      'teaser.feature3.title': fields.text({ label: 'teaser ➔ feature3 ➔ title' }),
      'teaser.feature3.desc': fields.text({ label: 'teaser ➔ feature3 ➔ desc' }),
      'teaser.store.apple': fields.text({ label: 'teaser ➔ store ➔ apple' }),
      'teaser.store.google': fields.text({ label: 'teaser ➔ store ➔ google' }),
      'cookie-policy.ab1cd2': fields.text({ label: 'cookie-policy ➔ ab1cd2' }),
      'refund-policy.xyz890': fields.text({ label: 'refund-policy ➔ xyz890' }),
      'terms.of.service.k92nsi': fields.text({ label: 'terms ➔ of ➔ service ➔ k92nsi' }),
      'marquee.1': fields.text({ label: 'marquee ➔ item 1' }),
      'marquee.2': fields.text({ label: 'marquee ➔ item 2' }),
      'marquee.3': fields.text({ label: 'marquee ➔ item 3' }),
      'marquee.4': fields.text({ label: 'marquee ➔ item 4' }),
      'marquee.5': fields.text({ label: 'marquee ➔ item 5' }),
    }
    }),
    enTranslations: singleton({
      label: 'English Translations (en.json)',
      path: 'src/dictionaries/en',
      format: { data: 'json' },
      schema: {
      'nav.home': fields.text({ label: 'nav ➔ home' }),
      'nav.services': fields.text({ label: 'nav ➔ services' }),
      'nav.families': fields.text({ label: 'nav ➔ families' }),
      'nav.companies': fields.text({ label: 'nav ➔ companies' }),
      'nav.caretakers': fields.text({ label: 'nav ➔ caretakers' }),
      'nav.institutions': fields.text({ label: 'nav ➔ institutions' }),
      'nav.howItWorks': fields.text({ label: 'nav ➔ how It Works' }),
      'nav.about': fields.text({ label: 'nav ➔ about' }),
      'nav.targetGroups': fields.text({ label: 'nav ➔ target Groups' }),
      'nav.contact': fields.text({ label: 'nav ➔ contact' }),
      'btn.login': fields.text({ label: 'btn ➔ login' }),
      'btn.signup': fields.text({ label: 'btn ➔ signup' }),
      'hero.title': fields.text({ label: 'hero ➔ title' }),
      'hero.subtitle': fields.text({ label: 'hero ➔ subtitle' }),
      'hero.cta.primary': fields.text({ label: 'hero ➔ cta ➔ primary' }),
      'hero.cta.secondary': fields.text({ label: 'hero ➔ cta ➔ secondary' }),
      'howitworks.eyebrow': fields.text({ label: 'howitworks ➔ eyebrow' }),
      'howitworks.title': fields.text({ label: 'howitworks ➔ title' }),
      'howitworks.subtitle': fields.text({ label: 'howitworks ➔ subtitle' }),
      'howitworks.steps.title': fields.text({ label: 'howitworks ➔ steps ➔ title' }),
      'howitworks.steps.subtitle': fields.text({ label: 'howitworks ➔ steps ➔ subtitle' }),
      'howitworks.step1.title': fields.text({ label: 'howitworks ➔ step1 ➔ title' }),
      'howitworks.step1.desc': fields.text({ label: 'howitworks ➔ step1 ➔ desc' }),
      'howitworks.step2.title': fields.text({ label: 'howitworks ➔ step2 ➔ title' }),
      'howitworks.step2.desc': fields.text({ label: 'howitworks ➔ step2 ➔ desc' }),
      'howitworks.step3.title': fields.text({ label: 'howitworks ➔ step3 ➔ title' }),
      'howitworks.step3.desc': fields.text({ label: 'howitworks ➔ step3 ➔ desc' }),
      'howitworks.step4.title': fields.text({ label: 'howitworks ➔ step4 ➔ title' }),
      'howitworks.step4.desc': fields.text({ label: 'howitworks ➔ step4 ➔ desc' }),
      'howitworks.features.title': fields.text({ label: 'howitworks ➔ features ➔ title' }),
      'howitworks.features.subtitle': fields.text({ label: 'howitworks ➔ features ➔ subtitle' }),
      'howitworks.feature1.title': fields.text({ label: 'howitworks ➔ feature1 ➔ title' }),
      'howitworks.feature1.desc': fields.text({ label: 'howitworks ➔ feature1 ➔ desc' }),
      'howitworks.feature2.title': fields.text({ label: 'howitworks ➔ feature2 ➔ title' }),
      'howitworks.feature2.desc': fields.text({ label: 'howitworks ➔ feature2 ➔ desc' }),
      'howitworks.feature3.title': fields.text({ label: 'howitworks ➔ feature3 ➔ title' }),
      'howitworks.feature3.desc': fields.text({ label: 'howitworks ➔ feature3 ➔ desc' }),
      'howitworks.feature4.title': fields.text({ label: 'howitworks ➔ feature4 ➔ title' }),
      'howitworks.feature4.desc': fields.text({ label: 'howitworks ➔ feature4 ➔ desc' }),
      'howitworks.feature5.title': fields.text({ label: 'howitworks ➔ feature5 ➔ title' }),
      'howitworks.feature5.desc': fields.text({ label: 'howitworks ➔ feature5 ➔ desc' }),
      'howitworks.feature6.title': fields.text({ label: 'howitworks ➔ feature6 ➔ title' }),
      'howitworks.feature6.desc': fields.text({ label: 'howitworks ➔ feature6 ➔ desc' }),
      'howitworks.testimonials.title': fields.text({ label: 'howitworks ➔ testimonials ➔ title' }),
      'howitworks.testimonials.subtitle': fields.text({ label: 'howitworks ➔ testimonials ➔ subtitle' }),
      'howitworks.testimonial1': fields.text({ label: 'howitworks ➔ testimonial1' }),
      'howitworks.testimonial2': fields.text({ label: 'howitworks ➔ testimonial2' }),
      'howitworks.testimonial3': fields.text({ label: 'howitworks ➔ testimonial3' }),
      'howitworks.cta.title': fields.text({ label: 'howitworks ➔ cta ➔ title' }),
      'howitworks.cta.subtitle': fields.text({ label: 'howitworks ➔ cta ➔ subtitle' }),
      'howitworks.cta.primary': fields.text({ label: 'howitworks ➔ cta ➔ primary' }),
      'howitworks.cta.secondary': fields.text({ label: 'howitworks ➔ cta ➔ secondary' }),
      'plans.eyebrow': fields.text({ label: 'plans ➔ eyebrow' }),
      'plans.title': fields.text({ label: 'plans ➔ title' }),
      'plans.subtitle': fields.text({ label: 'plans ➔ subtitle' }),
      'plans.basic.title': fields.text({ label: 'plans ➔ basic ➔ title' }),
      'plans.basic.desc': fields.text({ label: 'plans ➔ basic ➔ desc' }),
      'plans.premium.title': fields.text({ label: 'plans ➔ premium ➔ title' }),
      'plans.premium.desc': fields.text({ label: 'plans ➔ premium ➔ desc' }),
      'btn.register': fields.text({ label: 'btn ➔ register' }),
      'app.eyebrow': fields.text({ label: 'app ➔ eyebrow' }),
      'app.title': fields.text({ label: 'app ➔ title' }),
      'app.subtitle': fields.text({ label: 'app ➔ subtitle' }),
      'app.apple': fields.text({ label: 'app ➔ apple' }),
      'app.google': fields.text({ label: 'app ➔ google' }),
      'cta.final': fields.text({ label: 'cta ➔ final' }),
      'btn.contact': fields.text({ label: 'btn ➔ contact' }),
      'families.8obkup': fields.text({ label: 'families ➔ 8obkup' }),
      'families.g98to4': fields.text({ label: 'families ➔ g98to4' }),
      'families.qec43n': fields.text({ label: 'families ➔ qec43n' }),
      'families.hxhsi0': fields.text({ label: 'families ➔ hxhsi0' }),
      'families.4rf7pp': fields.text({ label: 'families ➔ 4rf7pp' }),
      'families.hj40w3': fields.text({ label: 'families ➔ hj40w3' }),
      'families.ffxrqu': fields.text({ label: 'families ➔ ffxrqu' }),
      'families.rnq6i6': fields.text({ label: 'families ➔ rnq6i6' }),
      'families.1vttbc': fields.text({ label: 'families ➔ 1vttbc' }),
      'btn.baz63n': fields.text({ label: 'btn ➔ baz63n' }),
      'btn.tajlr7': fields.text({ label: 'btn ➔ tajlr7' }),
      'btn.kbxonb': fields.text({ label: 'btn ➔ kbxonb' }),
      'btn.ss7pm7': fields.text({ label: 'btn ➔ ss7pm7' }),
      'business.yucpi8': fields.text({ label: 'business ➔ yucpi8' }),
      'business.jfxwf7': fields.text({ label: 'business ➔ jfxwf7' }),
      'business.2cyre1': fields.text({ label: 'business ➔ 2cyre1' }),
      'business.ylyczm': fields.text({ label: 'business ➔ ylyczm' }),
      'business.ffxrqu': fields.text({ label: 'business ➔ ffxrqu' }),
      'business.rnq6i6': fields.text({ label: 'business ➔ rnq6i6' }),
      'business.1vttbc': fields.text({ label: 'business ➔ 1vttbc' }),
      'institutions.db2gj4': fields.text({ label: 'institutions ➔ db2gj4' }),
      'institutions.qapkqs': fields.text({ label: 'institutions ➔ qapkqs' }),
      'institutions.r1j4o5': fields.text({ label: 'institutions ➔ r1j4o5' }),
      'institutions.3dylv3': fields.text({ label: 'institutions ➔ 3dylv3' }),
      'institutions.rnq6i6': fields.text({ label: 'institutions ➔ rnq6i6' }),
      'institutions.1vttbc': fields.text({ label: 'institutions ➔ 1vttbc' }),
      'btn.za3mim': fields.text({ label: 'btn ➔ za3mim' }),
      'btn.wxrlhb': fields.text({ label: 'btn ➔ wxrlhb' }),
      'providers.tgm1nq': fields.text({ label: 'providers ➔ tgm1nq' }),
      'providers.1ep91': fields.text({ label: 'providers ➔ 1ep91' }),
      'providers.9qrh41': fields.text({ label: 'providers ➔ 9qrh41' }),
      'providers.rnq6i6': fields.text({ label: 'providers ➔ rnq6i6' }),
      'providers.1vttbc': fields.text({ label: 'providers ➔ 1vttbc' }),
      'btn.pjun8n': fields.text({ label: 'btn ➔ pjun8n' }),
      'btn.pjtzif': fields.text({ label: 'btn ➔ pjtzif' }),
      'about.lltg2z': fields.text({ label: 'about ➔ lltg2z' }),
      'about.5i94sz': fields.text({ label: 'about ➔ 5i94sz' }),
      'about.qje0vl': fields.text({ label: 'about ➔ qje0vl' }),
      'about.bmciuz': fields.text({ label: 'about ➔ bmciuz' }),
      'about.fyalyk': fields.text({ label: 'about ➔ fyalyk' }),
      'about.c8lysq': fields.text({ label: 'about ➔ c8lysq' }),
      'about.19u3im': fields.text({ label: 'about ➔ 19u3im' }),
      'about.ffnspn': fields.text({ label: 'about ➔ ffnspn' }),
      'about.g1bwny': fields.text({ label: 'about ➔ g1bwny' }),
      'about.xjr5ai': fields.text({ label: 'about ➔ xjr5ai' }),
      'about.k51ypq': fields.text({ label: 'about ➔ k51ypq' }),
      'about.mk7xo6': fields.text({ label: 'about ➔ mk7xo6' }),
      'about.twhsw8': fields.text({ label: 'about ➔ twhsw8' }),
      'about.7mf0mf': fields.text({ label: 'about ➔ 7mf0mf' }),
      'about.w395tm': fields.text({ label: 'about ➔ w395tm' }),
      'about.neplkz': fields.text({ label: 'about ➔ neplkz' }),
      'about.uqz92y': fields.text({ label: 'about ➔ uqz92y' }),
      'about.re1vey': fields.text({ label: 'about ➔ re1vey' }),
      'about.rnq6i6': fields.text({ label: 'about ➔ rnq6i6' }),
      'btn.9urml2': fields.text({ label: 'btn ➔ 9urml2' }),
      'contact.1tr8yh': fields.text({ label: 'contact ➔ 1tr8yh' }),
      'contact.frg0dp': fields.text({ label: 'contact ➔ frg0dp' }),
      'contact.rnq6i6': fields.text({ label: 'contact ➔ rnq6i6' }),
      'contact.1vttbc': fields.text({ label: 'contact ➔ 1vttbc' }),
      'imprint.bn9ct3': fields.text({ label: 'imprint ➔ bn9ct3' }),
      'imprint.5vhr4f': fields.text({ label: 'imprint ➔ 5vhr4f' }),
      'imprint.cnghov': fields.text({ label: 'imprint ➔ cnghov' }),
      'imprint.jjo9k2': fields.text({ label: 'imprint ➔ jjo9k2' }),
      'imprint.1vttbc': fields.text({ label: 'imprint ➔ 1vttbc' }),
      'privacy-policy.hop62e': fields.text({ label: 'privacy-policy ➔ hop62e' }),
      'privacy-policy.if995r': fields.text({ label: 'privacy-policy ➔ if995r' }),
      'privacy-policy.ry02dm': fields.text({ label: 'privacy-policy ➔ ry02dm' }),
      'privacy-policy.eniysn': fields.text({ label: 'privacy-policy ➔ eniysn' }),
      'privacy-policy.jh3mop': fields.text({ label: 'privacy-policy ➔ jh3mop' }),
      'privacy-policy.1tw77k': fields.text({ label: 'privacy-policy ➔ 1tw77k' }),
      'privacy-policy.spkljn': fields.text({ label: 'privacy-policy ➔ spkljn' }),
      'privacy-policy.7rv48p': fields.text({ label: 'privacy-policy ➔ 7rv48p' }),
      'privacy-policy.ecgqqb': fields.text({ label: 'privacy-policy ➔ ecgqqb' }),
      'privacy-policy.2h4v5g': fields.text({ label: 'privacy-policy ➔ 2h4v5g' }),
      'privacy-policy.mbws6u': fields.text({ label: 'privacy-policy ➔ mbws6u' }),
      'privacy-policy.n7kh4j': fields.text({ label: 'privacy-policy ➔ n7kh4j' }),
      'privacy-policy.qvfur5': fields.text({ label: 'privacy-policy ➔ qvfur5' }),
      'privacy-policy.ls2tnc': fields.text({ label: 'privacy-policy ➔ ls2tnc' }),
      'privacy-policy.nfj3mi': fields.text({ label: 'privacy-policy ➔ nfj3mi' }),
      'privacy-policy.ow8rze': fields.text({ label: 'privacy-policy ➔ ow8rze' }),
      'privacy-policy.n99qdx': fields.text({ label: 'privacy-policy ➔ n99qdx' }),
      'privacy-policy.ytl33c': fields.text({ label: 'privacy-policy ➔ ytl33c' }),
      'privacy-policy.51069v': fields.text({ label: 'privacy-policy ➔ 51069v' }),
      'privacy-policy.txt85s': fields.text({ label: 'privacy-policy ➔ txt85s' }),
      'privacy-policy.1vttbc': fields.text({ label: 'privacy-policy ➔ 1vttbc' }),
      'disclaimer-page.uwtyyt': fields.text({ label: 'disclaimer-page ➔ uwtyyt' }),
      'disclaimer-page.op3kb1': fields.text({ label: 'disclaimer-page ➔ op3kb1' }),
      'disclaimer-page.ahbulr': fields.text({ label: 'disclaimer-page ➔ ahbulr' }),
      'disclaimer-page.24ddz8': fields.text({ label: 'disclaimer-page ➔ 24ddz8' }),
      'disclaimer-page.6b333p': fields.text({ label: 'disclaimer-page ➔ 6b333p' }),
      'disclaimer-page.hhl8tl': fields.text({ label: 'disclaimer-page ➔ hhl8tl' }),
      'disclaimer-page.s9aat9': fields.text({ label: 'disclaimer-page ➔ s9aat9' }),
      'disclaimer-page.350ksq': fields.text({ label: 'disclaimer-page ➔ 350ksq' }),
      'disclaimer-page.numnp6': fields.text({ label: 'disclaimer-page ➔ numnp6' }),
      'disclaimer-page.aa0fux': fields.text({ label: 'disclaimer-page ➔ aa0fux' }),
      'disclaimer-page.l0g468': fields.text({ label: 'disclaimer-page ➔ l0g468' }),
      'disclaimer-page.8kpta6': fields.text({ label: 'disclaimer-page ➔ 8kpta6' }),
      'disclaimer-page.ajhmhl': fields.text({ label: 'disclaimer-page ➔ ajhmhl' }),
      'disclaimer-page.k5328e': fields.text({ label: 'disclaimer-page ➔ k5328e' }),
      'disclaimer-page.ef13ox': fields.text({ label: 'disclaimer-page ➔ ef13ox' }),
      'disclaimer-page.4vq4j4': fields.text({ label: 'disclaimer-page ➔ 4vq4j4' }),
      'disclaimer-page.rnq6i6': fields.text({ label: 'disclaimer-page ➔ rnq6i6' }),
      'disclaimer-page.1vttbc': fields.text({ label: 'disclaimer-page ➔ 1vttbc' }),
      'families.hero.badge': fields.text({ label: 'families ➔ hero ➔ badge' }),
      'families.hero.title1': fields.text({ label: 'families ➔ hero ➔ title1' }),
      'families.hero.title2': fields.text({ label: 'families ➔ hero ➔ title2' }),
      'families.hero.desc': fields.text({ label: 'families ➔ hero ➔ desc' }),
      'families.hero.cta': fields.text({ label: 'families ➔ hero ➔ cta' }),
      'families.how.title': fields.text({ label: 'families ➔ how ➔ title' }),
      'families.how.1.title': fields.text({ label: 'families ➔ how ➔ 1 ➔ title' }),
      'families.how.1.desc': fields.text({ label: 'families ➔ how ➔ 1 ➔ desc' }),
      'families.how.2.title': fields.text({ label: 'families ➔ how ➔ 2 ➔ title' }),
      'families.how.2.desc': fields.text({ label: 'families ➔ how ➔ 2 ➔ desc' }),
      'families.how.3.title': fields.text({ label: 'families ➔ how ➔ 3 ➔ title' }),
      'families.how.3.desc': fields.text({ label: 'families ➔ how ➔ 3 ➔ desc' }),
      'families.how.4.title': fields.text({ label: 'families ➔ how ➔ 4 ➔ title' }),
      'families.how.4.desc': fields.text({ label: 'families ➔ how ➔ 4 ➔ desc' }),
      'families.invite.title': fields.text({ label: 'families ➔ invite ➔ title' }),
      'families.invite.desc': fields.text({ label: 'families ➔ invite ➔ desc' }),
      'families.invite.cta': fields.text({ label: 'families ➔ invite ➔ cta' }),
      'families.know.title': fields.text({ label: 'families ➔ know ➔ title' }),
      'families.know.desc': fields.text({ label: 'families ➔ know ➔ desc' }),
      'families.know.cta': fields.text({ label: 'families ➔ know ➔ cta' }),
      'families.app.title': fields.text({ label: 'families ➔ app ➔ title' }),
      'families.app.desc': fields.text({ label: 'families ➔ app ➔ desc' }),
      'families.app.cta': fields.text({ label: 'families ➔ app ➔ cta' }),
      'business.hero.badge': fields.text({ label: 'business ➔ hero ➔ badge' }),
      'business.hero.title1': fields.text({ label: 'business ➔ hero ➔ title1' }),
      'business.hero.title2': fields.text({ label: 'business ➔ hero ➔ title2' }),
      'business.hero.desc': fields.text({ label: 'business ➔ hero ➔ desc' }),
      'business.hero.cta': fields.text({ label: 'business ➔ hero ➔ cta' }),
      'business.pillar1.title': fields.text({ label: 'business ➔ pillar1 ➔ title' }),
      'business.pillar1.desc': fields.text({ label: 'business ➔ pillar1 ➔ desc' }),
      'business.pillar2.title': fields.text({ label: 'business ➔ pillar2 ➔ title' }),
      'business.pillar2.desc': fields.text({ label: 'business ➔ pillar2 ➔ desc' }),
      'business.cta.title': fields.text({ label: 'business ➔ cta ➔ title' }),
      'business.cta.desc': fields.text({ label: 'business ➔ cta ➔ desc' }),
      'business.cta.btn': fields.text({ label: 'business ➔ cta ➔ btn' }),
      'institutions.hero.badge': fields.text({ label: 'institutions ➔ hero ➔ badge' }),
      'institutions.hero.title1': fields.text({ label: 'institutions ➔ hero ➔ title1' }),
      'institutions.hero.title2': fields.text({ label: 'institutions ➔ hero ➔ title2' }),
      'institutions.hero.desc': fields.text({ label: 'institutions ➔ hero ➔ desc' }),
      'institutions.hero.cta': fields.text({ label: 'institutions ➔ hero ➔ cta' }),
      'institutions.pillar1.title': fields.text({ label: 'institutions ➔ pillar1 ➔ title' }),
      'institutions.pillar1.desc': fields.text({ label: 'institutions ➔ pillar1 ➔ desc' }),
      'institutions.pillar2.title': fields.text({ label: 'institutions ➔ pillar2 ➔ title' }),
      'institutions.pillar2.desc': fields.text({ label: 'institutions ➔ pillar2 ➔ desc' }),
      'institutions.cta.title': fields.text({ label: 'institutions ➔ cta ➔ title' }),
      'institutions.cta.desc': fields.text({ label: 'institutions ➔ cta ➔ desc' }),
      'institutions.cta.btn': fields.text({ label: 'institutions ➔ cta ➔ btn' }),
      'institutions.steps.title': fields.text({ label: 'institutions ➔ steps ➔ title' }),
      'institutions.step1.title': fields.text({ label: 'institutions ➔ step1 ➔ title' }),
      'institutions.step1.desc': fields.text({ label: 'institutions ➔ step1 ➔ desc' }),
      'institutions.step2.title': fields.text({ label: 'institutions ➔ step2 ➔ title' }),
      'institutions.step2.desc': fields.text({ label: 'institutions ➔ step2 ➔ desc' }),
      'institutions.step3.title': fields.text({ label: 'institutions ➔ step3 ➔ title' }),
      'institutions.step3.desc': fields.text({ label: 'institutions ➔ step3 ➔ desc' }),
      'institutions.register.cta': fields.text({ label: 'institutions ➔ register ➔ cta' }),
      'providers.hero.badge': fields.text({ label: 'providers ➔ hero ➔ badge' }),
      'providers.hero.title1': fields.text({ label: 'providers ➔ hero ➔ title1' }),
      'providers.hero.title2': fields.text({ label: 'providers ➔ hero ➔ title2' }),
      'providers.hero.desc': fields.text({ label: 'providers ➔ hero ➔ desc' }),
      'providers.hero.cta': fields.text({ label: 'providers ➔ hero ➔ cta' }),
      'providers.steps.title': fields.text({ label: 'providers ➔ steps ➔ title' }),
      'providers.step1.title': fields.text({ label: 'providers ➔ step1 ➔ title' }),
      'providers.step1.desc': fields.text({ label: 'providers ➔ step1 ➔ desc' }),
      'providers.step2.title': fields.text({ label: 'providers ➔ step2 ➔ title' }),
      'providers.step2.desc': fields.text({ label: 'providers ➔ step2 ➔ desc' }),
      'providers.step3.title': fields.text({ label: 'providers ➔ step3 ➔ title' }),
      'providers.step3.desc': fields.text({ label: 'providers ➔ step3 ➔ desc' }),
      'providers.cta.title': fields.text({ label: 'providers ➔ cta ➔ title' }),
      'providers.cta.desc': fields.text({ label: 'providers ➔ cta ➔ desc' }),
      'providers.cta.btn': fields.text({ label: 'providers ➔ cta ➔ btn' }),
      'contact.badge': fields.text({ label: 'contact ➔ badge' }),
      'contact.title1': fields.text({ label: 'contact ➔ title1' }),
      'contact.title2': fields.text({ label: 'contact ➔ title2' }),
      'contact.desc': fields.text({ label: 'contact ➔ desc' }),
      'contact.email.title': fields.text({ label: 'contact ➔ email ➔ title' }),
      'contact.email.desc': fields.text({ label: 'contact ➔ email ➔ desc' }),
      'contact.phone.title': fields.text({ label: 'contact ➔ phone ➔ title' }),
      'contact.phone.desc': fields.text({ label: 'contact ➔ phone ➔ desc' }),
      'contact.office.title': fields.text({ label: 'contact ➔ office ➔ title' }),
      'contact.office.desc': fields.text({ label: 'contact ➔ office ➔ desc' }),
      'contact.newsletter.title': fields.text({ label: 'contact ➔ newsletter ➔ title' }),
      'contact.newsletter.desc': fields.text({ label: 'contact ➔ newsletter ➔ desc' }),
      'contact.newsletter.btn': fields.text({ label: 'contact ➔ newsletter ➔ btn' }),
      'providers.adv.title': fields.text({ label: 'providers ➔ adv ➔ title' }),
      'providers.adv.1.title': fields.text({ label: 'providers ➔ adv ➔ 1 ➔ title' }),
      'providers.adv.1.desc': fields.text({ label: 'providers ➔ adv ➔ 1 ➔ desc' }),
      'providers.adv.2.title': fields.text({ label: 'providers ➔ adv ➔ 2 ➔ title' }),
      'providers.adv.2.desc': fields.text({ label: 'providers ➔ adv ➔ 2 ➔ desc' }),
      'providers.adv.3.title': fields.text({ label: 'providers ➔ adv ➔ 3 ➔ title' }),
      'providers.adv.3.desc': fields.text({ label: 'providers ➔ adv ➔ 3 ➔ desc' }),
      'providers.adv.4.title': fields.text({ label: 'providers ➔ adv ➔ 4 ➔ title' }),
      'providers.adv.4.desc': fields.text({ label: 'providers ➔ adv ➔ 4 ➔ desc' }),
      'providers.app.title': fields.text({ label: 'providers ➔ app ➔ title' }),
      'providers.app.desc': fields.text({ label: 'providers ➔ app ➔ desc' }),
      'providers.app.cta': fields.text({ label: 'providers ➔ app ➔ cta' }),
      'about.label': fields.text({ label: 'about ➔ label' }),
      'about.impact': fields.text({ label: 'about ➔ impact' }),
      'contact.form.title': fields.text({ label: 'contact ➔ form ➔ title' }),
      'contact.form.desc': fields.text({ label: 'contact ➔ form ➔ desc' }),
      'contact.form.name.label': fields.text({ label: 'contact ➔ form ➔ name ➔ label' }),
      'contact.form.name.placeholder': fields.text({ label: 'contact ➔ form ➔ name ➔ placeholder' }),
      'contact.form.email.label': fields.text({ label: 'contact ➔ form ➔ email ➔ label' }),
      'contact.form.email.placeholder': fields.text({ label: 'contact ➔ form ➔ email ➔ placeholder' }),
      'contact.form.phone.label': fields.text({ label: 'contact ➔ form ➔ phone ➔ label' }),
      'contact.form.phone.placeholder': fields.text({ label: 'contact ➔ form ➔ phone ➔ placeholder' }),
      'contact.form.subject.label': fields.text({ label: 'contact ➔ form ➔ subject ➔ label' }),
      'contact.form.subject.placeholder': fields.text({ label: 'contact ➔ form ➔ subject ➔ placeholder' }),
      'contact.form.message.label': fields.text({ label: 'contact ➔ form ➔ message ➔ label' }),
      'contact.form.message.placeholder': fields.text({ label: 'contact ➔ form ➔ message ➔ placeholder' }),
      'contact.form.submit': fields.text({ label: 'contact ➔ form ➔ submit' }),
      'contact.newsletter.disclaimer': fields.text({ label: 'contact ➔ newsletter ➔ disclaimer' }),
      'teaser.badge': fields.text({ label: 'teaser ➔ badge' }),
      'teaser.title': fields.text({ label: 'teaser ➔ title' }),
      'teaser.desc': fields.text({ label: 'teaser ➔ desc' }),
      'teaser.feature1.title': fields.text({ label: 'teaser ➔ feature1 ➔ title' }),
      'teaser.feature1.desc': fields.text({ label: 'teaser ➔ feature1 ➔ desc' }),
      'teaser.feature2.title': fields.text({ label: 'teaser ➔ feature2 ➔ title' }),
      'teaser.feature2.desc': fields.text({ label: 'teaser ➔ feature2 ➔ desc' }),
      'teaser.feature3.title': fields.text({ label: 'teaser ➔ feature3 ➔ title' }),
      'teaser.feature3.desc': fields.text({ label: 'teaser ➔ feature3 ➔ desc' }),
      'teaser.store.apple': fields.text({ label: 'teaser ➔ store ➔ apple' }),
      'teaser.store.google': fields.text({ label: 'teaser ➔ store ➔ google' }),
      'cookie-policy.ab1cd2': fields.text({ label: 'cookie-policy ➔ ab1cd2' }),
      'refund-policy.xyz890': fields.text({ label: 'refund-policy ➔ xyz890' }),
      'terms.of.service.k92nsi': fields.text({ label: 'terms ➔ of ➔ service ➔ k92nsi' }),
      'marquee.1': fields.text({ label: 'marquee ➔ item 1' }),
      'marquee.2': fields.text({ label: 'marquee ➔ item 2' }),
      'marquee.3': fields.text({ label: 'marquee ➔ item 3' }),
      'marquee.4': fields.text({ label: 'marquee ➔ item 4' }),
      'marquee.5': fields.text({ label: 'marquee ➔ item 5' }),
    }
    }),
    hrTranslations: singleton({
      label: 'Hrvatski Prijevodi (hr.json)',
      path: 'src/dictionaries/hr',
      format: { data: 'json' },
      schema: {
      'nav.home': fields.text({ label: 'nav ➔ home' }),
      'nav.services': fields.text({ label: 'nav ➔ services' }),
      'nav.families': fields.text({ label: 'nav ➔ families' }),
      'nav.companies': fields.text({ label: 'nav ➔ companies' }),
      'nav.caretakers': fields.text({ label: 'nav ➔ caretakers' }),
      'nav.institutions': fields.text({ label: 'nav ➔ institutions' }),
      'nav.howItWorks': fields.text({ label: 'nav ➔ how It Works' }),
      'nav.about': fields.text({ label: 'nav ➔ about' }),
      'nav.targetGroups': fields.text({ label: 'nav ➔ target Groups' }),
      'nav.contact': fields.text({ label: 'nav ➔ contact' }),
      'btn.login': fields.text({ label: 'btn ➔ login' }),
      'btn.signup': fields.text({ label: 'btn ➔ signup' }),
      'hero.title': fields.text({ label: 'hero ➔ title' }),
      'hero.subtitle': fields.text({ label: 'hero ➔ subtitle' }),
      'hero.cta.primary': fields.text({ label: 'hero ➔ cta ➔ primary' }),
      'hero.cta.secondary': fields.text({ label: 'hero ➔ cta ➔ secondary' }),
      'howitworks.eyebrow': fields.text({ label: 'howitworks ➔ eyebrow' }),
      'howitworks.title': fields.text({ label: 'howitworks ➔ title' }),
      'howitworks.subtitle': fields.text({ label: 'howitworks ➔ subtitle' }),
      'howitworks.steps.title': fields.text({ label: 'howitworks ➔ steps ➔ title' }),
      'howitworks.steps.subtitle': fields.text({ label: 'howitworks ➔ steps ➔ subtitle' }),
      'howitworks.step1.title': fields.text({ label: 'howitworks ➔ step1 ➔ title' }),
      'howitworks.step1.desc': fields.text({ label: 'howitworks ➔ step1 ➔ desc' }),
      'howitworks.step2.title': fields.text({ label: 'howitworks ➔ step2 ➔ title' }),
      'howitworks.step2.desc': fields.text({ label: 'howitworks ➔ step2 ➔ desc' }),
      'howitworks.step3.title': fields.text({ label: 'howitworks ➔ step3 ➔ title' }),
      'howitworks.step3.desc': fields.text({ label: 'howitworks ➔ step3 ➔ desc' }),
      'howitworks.step4.title': fields.text({ label: 'howitworks ➔ step4 ➔ title' }),
      'howitworks.step4.desc': fields.text({ label: 'howitworks ➔ step4 ➔ desc' }),
      'howitworks.features.title': fields.text({ label: 'howitworks ➔ features ➔ title' }),
      'howitworks.features.subtitle': fields.text({ label: 'howitworks ➔ features ➔ subtitle' }),
      'howitworks.feature1.title': fields.text({ label: 'howitworks ➔ feature1 ➔ title' }),
      'howitworks.feature1.desc': fields.text({ label: 'howitworks ➔ feature1 ➔ desc' }),
      'howitworks.feature2.title': fields.text({ label: 'howitworks ➔ feature2 ➔ title' }),
      'howitworks.feature2.desc': fields.text({ label: 'howitworks ➔ feature2 ➔ desc' }),
      'howitworks.feature3.title': fields.text({ label: 'howitworks ➔ feature3 ➔ title' }),
      'howitworks.feature3.desc': fields.text({ label: 'howitworks ➔ feature3 ➔ desc' }),
      'howitworks.feature4.title': fields.text({ label: 'howitworks ➔ feature4 ➔ title' }),
      'howitworks.feature4.desc': fields.text({ label: 'howitworks ➔ feature4 ➔ desc' }),
      'howitworks.feature5.title': fields.text({ label: 'howitworks ➔ feature5 ➔ title' }),
      'howitworks.feature5.desc': fields.text({ label: 'howitworks ➔ feature5 ➔ desc' }),
      'howitworks.feature6.title': fields.text({ label: 'howitworks ➔ feature6 ➔ title' }),
      'howitworks.feature6.desc': fields.text({ label: 'howitworks ➔ feature6 ➔ desc' }),
      'howitworks.testimonials.title': fields.text({ label: 'howitworks ➔ testimonials ➔ title' }),
      'howitworks.testimonials.subtitle': fields.text({ label: 'howitworks ➔ testimonials ➔ subtitle' }),
      'howitworks.testimonial1': fields.text({ label: 'howitworks ➔ testimonial1' }),
      'howitworks.testimonial2': fields.text({ label: 'howitworks ➔ testimonial2' }),
      'howitworks.testimonial3': fields.text({ label: 'howitworks ➔ testimonial3' }),
      'howitworks.cta.title': fields.text({ label: 'howitworks ➔ cta ➔ title' }),
      'howitworks.cta.subtitle': fields.text({ label: 'howitworks ➔ cta ➔ subtitle' }),
      'howitworks.cta.primary': fields.text({ label: 'howitworks ➔ cta ➔ primary' }),
      'howitworks.cta.secondary': fields.text({ label: 'howitworks ➔ cta ➔ secondary' }),
      'plans.eyebrow': fields.text({ label: 'plans ➔ eyebrow' }),
      'plans.title': fields.text({ label: 'plans ➔ title' }),
      'plans.subtitle': fields.text({ label: 'plans ➔ subtitle' }),
      'plans.basic.title': fields.text({ label: 'plans ➔ basic ➔ title' }),
      'plans.basic.desc': fields.text({ label: 'plans ➔ basic ➔ desc' }),
      'plans.premium.title': fields.text({ label: 'plans ➔ premium ➔ title' }),
      'plans.premium.desc': fields.text({ label: 'plans ➔ premium ➔ desc' }),
      'btn.register': fields.text({ label: 'btn ➔ register' }),
      'app.eyebrow': fields.text({ label: 'app ➔ eyebrow' }),
      'app.title': fields.text({ label: 'app ➔ title' }),
      'app.subtitle': fields.text({ label: 'app ➔ subtitle' }),
      'app.apple': fields.text({ label: 'app ➔ apple' }),
      'app.google': fields.text({ label: 'app ➔ google' }),
      'cta.final': fields.text({ label: 'cta ➔ final' }),
      'btn.contact': fields.text({ label: 'btn ➔ contact' }),
      'families.8obkup': fields.text({ label: 'families ➔ 8obkup' }),
      'families.g98to4': fields.text({ label: 'families ➔ g98to4' }),
      'families.qec43n': fields.text({ label: 'families ➔ qec43n' }),
      'families.hxhsi0': fields.text({ label: 'families ➔ hxhsi0' }),
      'families.4rf7pp': fields.text({ label: 'families ➔ 4rf7pp' }),
      'families.hj40w3': fields.text({ label: 'families ➔ hj40w3' }),
      'families.ffxrqu': fields.text({ label: 'families ➔ ffxrqu' }),
      'families.rnq6i6': fields.text({ label: 'families ➔ rnq6i6' }),
      'families.1vttbc': fields.text({ label: 'families ➔ 1vttbc' }),
      'btn.baz63n': fields.text({ label: 'btn ➔ baz63n' }),
      'btn.tajlr7': fields.text({ label: 'btn ➔ tajlr7' }),
      'btn.kbxonb': fields.text({ label: 'btn ➔ kbxonb' }),
      'btn.ss7pm7': fields.text({ label: 'btn ➔ ss7pm7' }),
      'business.yucpi8': fields.text({ label: 'business ➔ yucpi8' }),
      'business.jfxwf7': fields.text({ label: 'business ➔ jfxwf7' }),
      'business.2cyre1': fields.text({ label: 'business ➔ 2cyre1' }),
      'business.ylyczm': fields.text({ label: 'business ➔ ylyczm' }),
      'business.ffxrqu': fields.text({ label: 'business ➔ ffxrqu' }),
      'business.rnq6i6': fields.text({ label: 'business ➔ rnq6i6' }),
      'business.1vttbc': fields.text({ label: 'business ➔ 1vttbc' }),
      'institutions.db2gj4': fields.text({ label: 'institutions ➔ db2gj4' }),
      'institutions.qapkqs': fields.text({ label: 'institutions ➔ qapkqs' }),
      'institutions.r1j4o5': fields.text({ label: 'institutions ➔ r1j4o5' }),
      'institutions.3dylv3': fields.text({ label: 'institutions ➔ 3dylv3' }),
      'institutions.rnq6i6': fields.text({ label: 'institutions ➔ rnq6i6' }),
      'institutions.1vttbc': fields.text({ label: 'institutions ➔ 1vttbc' }),
      'btn.za3mim': fields.text({ label: 'btn ➔ za3mim' }),
      'btn.wxrlhb': fields.text({ label: 'btn ➔ wxrlhb' }),
      'providers.tgm1nq': fields.text({ label: 'providers ➔ tgm1nq' }),
      'providers.1ep91': fields.text({ label: 'providers ➔ 1ep91' }),
      'providers.9qrh41': fields.text({ label: 'providers ➔ 9qrh41' }),
      'providers.rnq6i6': fields.text({ label: 'providers ➔ rnq6i6' }),
      'providers.1vttbc': fields.text({ label: 'providers ➔ 1vttbc' }),
      'btn.pjun8n': fields.text({ label: 'btn ➔ pjun8n' }),
      'btn.pjtzif': fields.text({ label: 'btn ➔ pjtzif' }),
      'about.lltg2z': fields.text({ label: 'about ➔ lltg2z' }),
      'about.5i94sz': fields.text({ label: 'about ➔ 5i94sz' }),
      'about.qje0vl': fields.text({ label: 'about ➔ qje0vl' }),
      'about.bmciuz': fields.text({ label: 'about ➔ bmciuz' }),
      'about.fyalyk': fields.text({ label: 'about ➔ fyalyk' }),
      'about.c8lysq': fields.text({ label: 'about ➔ c8lysq' }),
      'about.19u3im': fields.text({ label: 'about ➔ 19u3im' }),
      'about.ffnspn': fields.text({ label: 'about ➔ ffnspn' }),
      'about.g1bwny': fields.text({ label: 'about ➔ g1bwny' }),
      'about.xjr5ai': fields.text({ label: 'about ➔ xjr5ai' }),
      'about.k51ypq': fields.text({ label: 'about ➔ k51ypq' }),
      'about.mk7xo6': fields.text({ label: 'about ➔ mk7xo6' }),
      'about.twhsw8': fields.text({ label: 'about ➔ twhsw8' }),
      'about.7mf0mf': fields.text({ label: 'about ➔ 7mf0mf' }),
      'about.w395tm': fields.text({ label: 'about ➔ w395tm' }),
      'about.neplkz': fields.text({ label: 'about ➔ neplkz' }),
      'about.uqz92y': fields.text({ label: 'about ➔ uqz92y' }),
      'about.re1vey': fields.text({ label: 'about ➔ re1vey' }),
      'about.rnq6i6': fields.text({ label: 'about ➔ rnq6i6' }),
      'btn.9urml2': fields.text({ label: 'btn ➔ 9urml2' }),
      'contact.1tr8yh': fields.text({ label: 'contact ➔ 1tr8yh' }),
      'contact.frg0dp': fields.text({ label: 'contact ➔ frg0dp' }),
      'contact.rnq6i6': fields.text({ label: 'contact ➔ rnq6i6' }),
      'contact.1vttbc': fields.text({ label: 'contact ➔ 1vttbc' }),
      'imprint.bn9ct3': fields.text({ label: 'imprint ➔ bn9ct3' }),
      'imprint.5vhr4f': fields.text({ label: 'imprint ➔ 5vhr4f' }),
      'imprint.cnghov': fields.text({ label: 'imprint ➔ cnghov' }),
      'imprint.jjo9k2': fields.text({ label: 'imprint ➔ jjo9k2' }),
      'imprint.1vttbc': fields.text({ label: 'imprint ➔ 1vttbc' }),
      'privacy-policy.hop62e': fields.text({ label: 'privacy-policy ➔ hop62e' }),
      'privacy-policy.if995r': fields.text({ label: 'privacy-policy ➔ if995r' }),
      'privacy-policy.ry02dm': fields.text({ label: 'privacy-policy ➔ ry02dm' }),
      'privacy-policy.eniysn': fields.text({ label: 'privacy-policy ➔ eniysn' }),
      'privacy-policy.jh3mop': fields.text({ label: 'privacy-policy ➔ jh3mop' }),
      'privacy-policy.1tw77k': fields.text({ label: 'privacy-policy ➔ 1tw77k' }),
      'privacy-policy.spkljn': fields.text({ label: 'privacy-policy ➔ spkljn' }),
      'privacy-policy.7rv48p': fields.text({ label: 'privacy-policy ➔ 7rv48p' }),
      'privacy-policy.ecgqqb': fields.text({ label: 'privacy-policy ➔ ecgqqb' }),
      'privacy-policy.2h4v5g': fields.text({ label: 'privacy-policy ➔ 2h4v5g' }),
      'privacy-policy.mbws6u': fields.text({ label: 'privacy-policy ➔ mbws6u' }),
      'privacy-policy.n7kh4j': fields.text({ label: 'privacy-policy ➔ n7kh4j' }),
      'privacy-policy.qvfur5': fields.text({ label: 'privacy-policy ➔ qvfur5' }),
      'privacy-policy.ls2tnc': fields.text({ label: 'privacy-policy ➔ ls2tnc' }),
      'privacy-policy.nfj3mi': fields.text({ label: 'privacy-policy ➔ nfj3mi' }),
      'privacy-policy.ow8rze': fields.text({ label: 'privacy-policy ➔ ow8rze' }),
      'privacy-policy.n99qdx': fields.text({ label: 'privacy-policy ➔ n99qdx' }),
      'privacy-policy.ytl33c': fields.text({ label: 'privacy-policy ➔ ytl33c' }),
      'privacy-policy.51069v': fields.text({ label: 'privacy-policy ➔ 51069v' }),
      'privacy-policy.txt85s': fields.text({ label: 'privacy-policy ➔ txt85s' }),
      'privacy-policy.1vttbc': fields.text({ label: 'privacy-policy ➔ 1vttbc' }),
      'disclaimer-page.uwtyyt': fields.text({ label: 'disclaimer-page ➔ uwtyyt' }),
      'disclaimer-page.op3kb1': fields.text({ label: 'disclaimer-page ➔ op3kb1' }),
      'disclaimer-page.ahbulr': fields.text({ label: 'disclaimer-page ➔ ahbulr' }),
      'disclaimer-page.24ddz8': fields.text({ label: 'disclaimer-page ➔ 24ddz8' }),
      'disclaimer-page.6b333p': fields.text({ label: 'disclaimer-page ➔ 6b333p' }),
      'disclaimer-page.hhl8tl': fields.text({ label: 'disclaimer-page ➔ hhl8tl' }),
      'disclaimer-page.s9aat9': fields.text({ label: 'disclaimer-page ➔ s9aat9' }),
      'disclaimer-page.350ksq': fields.text({ label: 'disclaimer-page ➔ 350ksq' }),
      'disclaimer-page.numnp6': fields.text({ label: 'disclaimer-page ➔ numnp6' }),
      'disclaimer-page.aa0fux': fields.text({ label: 'disclaimer-page ➔ aa0fux' }),
      'disclaimer-page.l0g468': fields.text({ label: 'disclaimer-page ➔ l0g468' }),
      'disclaimer-page.8kpta6': fields.text({ label: 'disclaimer-page ➔ 8kpta6' }),
      'disclaimer-page.ajhmhl': fields.text({ label: 'disclaimer-page ➔ ajhmhl' }),
      'disclaimer-page.k5328e': fields.text({ label: 'disclaimer-page ➔ k5328e' }),
      'disclaimer-page.ef13ox': fields.text({ label: 'disclaimer-page ➔ ef13ox' }),
      'disclaimer-page.4vq4j4': fields.text({ label: 'disclaimer-page ➔ 4vq4j4' }),
      'disclaimer-page.rnq6i6': fields.text({ label: 'disclaimer-page ➔ rnq6i6' }),
      'disclaimer-page.1vttbc': fields.text({ label: 'disclaimer-page ➔ 1vttbc' }),
      'families.hero.badge': fields.text({ label: 'families ➔ hero ➔ badge' }),
      'families.hero.title1': fields.text({ label: 'families ➔ hero ➔ title1' }),
      'families.hero.title2': fields.text({ label: 'families ➔ hero ➔ title2' }),
      'families.hero.desc': fields.text({ label: 'families ➔ hero ➔ desc' }),
      'families.hero.cta': fields.text({ label: 'families ➔ hero ➔ cta' }),
      'families.how.title': fields.text({ label: 'families ➔ how ➔ title' }),
      'families.how.1.title': fields.text({ label: 'families ➔ how ➔ 1 ➔ title' }),
      'families.how.1.desc': fields.text({ label: 'families ➔ how ➔ 1 ➔ desc' }),
      'families.how.2.title': fields.text({ label: 'families ➔ how ➔ 2 ➔ title' }),
      'families.how.2.desc': fields.text({ label: 'families ➔ how ➔ 2 ➔ desc' }),
      'families.how.3.title': fields.text({ label: 'families ➔ how ➔ 3 ➔ title' }),
      'families.how.3.desc': fields.text({ label: 'families ➔ how ➔ 3 ➔ desc' }),
      'families.how.4.title': fields.text({ label: 'families ➔ how ➔ 4 ➔ title' }),
      'families.how.4.desc': fields.text({ label: 'families ➔ how ➔ 4 ➔ desc' }),
      'families.invite.title': fields.text({ label: 'families ➔ invite ➔ title' }),
      'families.invite.desc': fields.text({ label: 'families ➔ invite ➔ desc' }),
      'families.invite.cta': fields.text({ label: 'families ➔ invite ➔ cta' }),
      'families.know.title': fields.text({ label: 'families ➔ know ➔ title' }),
      'families.know.desc': fields.text({ label: 'families ➔ know ➔ desc' }),
      'families.know.cta': fields.text({ label: 'families ➔ know ➔ cta' }),
      'families.app.title': fields.text({ label: 'families ➔ app ➔ title' }),
      'families.app.desc': fields.text({ label: 'families ➔ app ➔ desc' }),
      'families.app.cta': fields.text({ label: 'families ➔ app ➔ cta' }),
      'business.hero.badge': fields.text({ label: 'business ➔ hero ➔ badge' }),
      'business.hero.title1': fields.text({ label: 'business ➔ hero ➔ title1' }),
      'business.hero.title2': fields.text({ label: 'business ➔ hero ➔ title2' }),
      'business.hero.desc': fields.text({ label: 'business ➔ hero ➔ desc' }),
      'business.hero.cta': fields.text({ label: 'business ➔ hero ➔ cta' }),
      'business.pillar1.title': fields.text({ label: 'business ➔ pillar1 ➔ title' }),
      'business.pillar1.desc': fields.text({ label: 'business ➔ pillar1 ➔ desc' }),
      'business.pillar2.title': fields.text({ label: 'business ➔ pillar2 ➔ title' }),
      'business.pillar2.desc': fields.text({ label: 'business ➔ pillar2 ➔ desc' }),
      'business.cta.title': fields.text({ label: 'business ➔ cta ➔ title' }),
      'business.cta.desc': fields.text({ label: 'business ➔ cta ➔ desc' }),
      'business.cta.btn': fields.text({ label: 'business ➔ cta ➔ btn' }),
      'institutions.hero.badge': fields.text({ label: 'institutions ➔ hero ➔ badge' }),
      'institutions.hero.title1': fields.text({ label: 'institutions ➔ hero ➔ title1' }),
      'institutions.hero.title2': fields.text({ label: 'institutions ➔ hero ➔ title2' }),
      'institutions.hero.desc': fields.text({ label: 'institutions ➔ hero ➔ desc' }),
      'institutions.hero.cta': fields.text({ label: 'institutions ➔ hero ➔ cta' }),
      'institutions.pillar1.title': fields.text({ label: 'institutions ➔ pillar1 ➔ title' }),
      'institutions.pillar1.desc': fields.text({ label: 'institutions ➔ pillar1 ➔ desc' }),
      'institutions.pillar2.title': fields.text({ label: 'institutions ➔ pillar2 ➔ title' }),
      'institutions.pillar2.desc': fields.text({ label: 'institutions ➔ pillar2 ➔ desc' }),
      'institutions.cta.title': fields.text({ label: 'institutions ➔ cta ➔ title' }),
      'institutions.cta.desc': fields.text({ label: 'institutions ➔ cta ➔ desc' }),
      'institutions.cta.btn': fields.text({ label: 'institutions ➔ cta ➔ btn' }),
      'institutions.steps.title': fields.text({ label: 'institutions ➔ steps ➔ title' }),
      'institutions.step1.title': fields.text({ label: 'institutions ➔ step1 ➔ title' }),
      'institutions.step1.desc': fields.text({ label: 'institutions ➔ step1 ➔ desc' }),
      'institutions.step2.title': fields.text({ label: 'institutions ➔ step2 ➔ title' }),
      'institutions.step2.desc': fields.text({ label: 'institutions ➔ step2 ➔ desc' }),
      'institutions.step3.title': fields.text({ label: 'institutions ➔ step3 ➔ title' }),
      'institutions.step3.desc': fields.text({ label: 'institutions ➔ step3 ➔ desc' }),
      'institutions.register.cta': fields.text({ label: 'institutions ➔ register ➔ cta' }),
      'providers.hero.badge': fields.text({ label: 'providers ➔ hero ➔ badge' }),
      'providers.hero.title1': fields.text({ label: 'providers ➔ hero ➔ title1' }),
      'providers.hero.title2': fields.text({ label: 'providers ➔ hero ➔ title2' }),
      'providers.hero.desc': fields.text({ label: 'providers ➔ hero ➔ desc' }),
      'providers.hero.cta': fields.text({ label: 'providers ➔ hero ➔ cta' }),
      'providers.steps.title': fields.text({ label: 'providers ➔ steps ➔ title' }),
      'providers.step1.title': fields.text({ label: 'providers ➔ step1 ➔ title' }),
      'providers.step1.desc': fields.text({ label: 'providers ➔ step1 ➔ desc' }),
      'providers.step2.title': fields.text({ label: 'providers ➔ step2 ➔ title' }),
      'providers.step2.desc': fields.text({ label: 'providers ➔ step2 ➔ desc' }),
      'providers.step3.title': fields.text({ label: 'providers ➔ step3 ➔ title' }),
      'providers.step3.desc': fields.text({ label: 'providers ➔ step3 ➔ desc' }),
      'providers.cta.title': fields.text({ label: 'providers ➔ cta ➔ title' }),
      'providers.cta.desc': fields.text({ label: 'providers ➔ cta ➔ desc' }),
      'providers.cta.btn': fields.text({ label: 'providers ➔ cta ➔ btn' }),
      'contact.badge': fields.text({ label: 'contact ➔ badge' }),
      'contact.title1': fields.text({ label: 'contact ➔ title1' }),
      'contact.title2': fields.text({ label: 'contact ➔ title2' }),
      'contact.desc': fields.text({ label: 'contact ➔ desc' }),
      'contact.email.title': fields.text({ label: 'contact ➔ email ➔ title' }),
      'contact.email.desc': fields.text({ label: 'contact ➔ email ➔ desc' }),
      'contact.phone.title': fields.text({ label: 'contact ➔ phone ➔ title' }),
      'contact.phone.desc': fields.text({ label: 'contact ➔ phone ➔ desc' }),
      'contact.office.title': fields.text({ label: 'contact ➔ office ➔ title' }),
      'contact.office.desc': fields.text({ label: 'contact ➔ office ➔ desc' }),
      'contact.newsletter.title': fields.text({ label: 'contact ➔ newsletter ➔ title' }),
      'contact.newsletter.desc': fields.text({ label: 'contact ➔ newsletter ➔ desc' }),
      'contact.newsletter.btn': fields.text({ label: 'contact ➔ newsletter ➔ btn' }),
      'providers.adv.title': fields.text({ label: 'providers ➔ adv ➔ title' }),
      'providers.adv.1.title': fields.text({ label: 'providers ➔ adv ➔ 1 ➔ title' }),
      'providers.adv.1.desc': fields.text({ label: 'providers ➔ adv ➔ 1 ➔ desc' }),
      'providers.adv.2.title': fields.text({ label: 'providers ➔ adv ➔ 2 ➔ title' }),
      'providers.adv.2.desc': fields.text({ label: 'providers ➔ adv ➔ 2 ➔ desc' }),
      'providers.adv.3.title': fields.text({ label: 'providers ➔ adv ➔ 3 ➔ title' }),
      'providers.adv.3.desc': fields.text({ label: 'providers ➔ adv ➔ 3 ➔ desc' }),
      'providers.adv.4.title': fields.text({ label: 'providers ➔ adv ➔ 4 ➔ title' }),
      'providers.adv.4.desc': fields.text({ label: 'providers ➔ adv ➔ 4 ➔ desc' }),
      'providers.app.title': fields.text({ label: 'providers ➔ app ➔ title' }),
      'providers.app.desc': fields.text({ label: 'providers ➔ app ➔ desc' }),
      'providers.app.cta': fields.text({ label: 'providers ➔ app ➔ cta' }),
      'about.label': fields.text({ label: 'about ➔ label' }),
      'about.impact': fields.text({ label: 'about ➔ impact' }),
      'contact.form.title': fields.text({ label: 'contact ➔ form ➔ title' }),
      'contact.form.desc': fields.text({ label: 'contact ➔ form ➔ desc' }),
      'contact.form.name.label': fields.text({ label: 'contact ➔ form ➔ name ➔ label' }),
      'contact.form.name.placeholder': fields.text({ label: 'contact ➔ form ➔ name ➔ placeholder' }),
      'contact.form.email.label': fields.text({ label: 'contact ➔ form ➔ email ➔ label' }),
      'contact.form.email.placeholder': fields.text({ label: 'contact ➔ form ➔ email ➔ placeholder' }),
      'contact.form.phone.label': fields.text({ label: 'contact ➔ form ➔ phone ➔ label' }),
      'contact.form.phone.placeholder': fields.text({ label: 'contact ➔ form ➔ phone ➔ placeholder' }),
      'contact.form.subject.label': fields.text({ label: 'contact ➔ form ➔ subject ➔ label' }),
      'contact.form.subject.placeholder': fields.text({ label: 'contact ➔ form ➔ subject ➔ placeholder' }),
      'contact.form.message.label': fields.text({ label: 'contact ➔ form ➔ message ➔ label' }),
      'contact.form.message.placeholder': fields.text({ label: 'contact ➔ form ➔ message ➔ placeholder' }),
      'contact.form.submit': fields.text({ label: 'contact ➔ form ➔ submit' }),
      'contact.newsletter.disclaimer': fields.text({ label: 'contact ➔ newsletter ➔ disclaimer' }),
      'teaser.badge': fields.text({ label: 'teaser ➔ badge' }),
      'teaser.title': fields.text({ label: 'teaser ➔ title' }),
      'teaser.desc': fields.text({ label: 'teaser ➔ desc' }),
      'teaser.feature1.title': fields.text({ label: 'teaser ➔ feature1 ➔ title' }),
      'teaser.feature1.desc': fields.text({ label: 'teaser ➔ feature1 ➔ desc' }),
      'teaser.feature2.title': fields.text({ label: 'teaser ➔ feature2 ➔ title' }),
      'teaser.feature2.desc': fields.text({ label: 'teaser ➔ feature2 ➔ desc' }),
      'teaser.feature3.title': fields.text({ label: 'teaser ➔ feature3 ➔ title' }),
      'teaser.feature3.desc': fields.text({ label: 'teaser ➔ feature3 ➔ desc' }),
      'teaser.store.apple': fields.text({ label: 'teaser ➔ store ➔ apple' }),
      'teaser.store.google': fields.text({ label: 'teaser ➔ store ➔ google' }),
      'cookie-policy.ab1cd2': fields.text({ label: 'cookie-policy ➔ ab1cd2' }),
      'refund-policy.xyz890': fields.text({ label: 'refund-policy ➔ xyz890' }),
      'terms.of.service.k92nsi': fields.text({ label: 'terms ➔ of ➔ service ➔ k92nsi' }),
      'marquee.1': fields.text({ label: 'marquee ➔ item 1' }),
      'marquee.2': fields.text({ label: 'marquee ➔ item 2' }),
      'marquee.3': fields.text({ label: 'marquee ➔ item 3' }),
      'marquee.4': fields.text({ label: 'marquee ➔ item 4' }),
      'marquee.5': fields.text({ label: 'marquee ➔ item 5' }),
    }
    }),
    pageImages: singleton({
      label: 'Bilder verwalten',
      path: 'src/content/images',
      format: { data: 'json' },
      schema: {
        homeHero: fields.image({
          label: 'Startseite Hero Bild (Home_hero2.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        registerHero: fields.image({
          label: 'Registrierungs-Sektion Bild (Hero_Register.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        aboutHero: fields.image({
          label: 'Über Uns Hero Bild (About_Hero2.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        howItWorksHero: fields.image({
          label: 'Wie es funktioniert Hero Bild (How_it_Works_Hero2.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        readyToBeginHero: fields.image({
          label: 'Bereit zu beginnen Bild (How_it_Works_Ready_to_Begin.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        familiesHero: fields.image({
          label: 'Familien Hero Bild (hero_families.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        familiesInvite: fields.image({
          label: 'Familien Einladen Hintergrund (families_invite_bg.jpg)',
          directory: 'public',
          publicPath: '/',
        }),
        familiesCaretaker: fields.image({
          label: 'Familien Grabpfleger Hintergrund (invite_them_to_oaza_mira_main.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        providersHero: fields.image({
          label: 'Dienstleister Hero Bild (hero_caretakers.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        businessHero: fields.image({
          label: 'Unternehmen Hero Bild (hero_business.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        institutionsHero: fields.image({
          label: 'Institutionen Hero Bild (hero_institutions.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        institutionsSec2: fields.image({
          label: 'Institutionen Was wir tun (what_we_do_fv.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        aboutCareHands: fields.image({
          label: 'Über Uns Care Hands Bild (platform_not_a_provider_main.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        aboutWhatWeDo: fields.image({
          label: 'Über Uns Was wir tun (about_what_we_do.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        aboutWhatWeDontDo: fields.image({
          label: 'Über Uns Was wir nicht tun (about_what_we_dont_do.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        aboutSeeHowBg: fields.image({
          label: 'Über Uns See How Background (about_see_how_bg.webp)',
          directory: 'public',
          publicPath: '/',
        }),
        howItWorksCtaBg: fields.image({
          label: 'Wie es funktioniert CTA Hintergrund (cta-bg.png)',
          directory: 'public',
          publicPath: '/',
        })
      }
    })
  }
});
